### ISSUE TITLE
Hi there ~

### ISSUE THREAD

**Issue by xieyuheng** [maxdee/freeliner-rs#1]
Hi there ~

I am Xie Yuheng (a friend of @myf)
I am also learning rust.
I like your project, if needed I can help you review rust code.
(you can @ me in your PR.)
you can also open issues and @ me there for questions.

**Comment by xieyuheng** [comment]
just to let you know I can help :)
closing it ~

**Comment by maxdee** [comment]
Hello! thanks for the offer :) happy to chat here for now. I think at this point I mostly have questions about architecture and stuff. Might do something like RFCs if people are interested in commenting.

**Comment by xieyuheng** [comment]
yes.
I can be your viewer of RFCs.
